### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by drazioti** [vamartid/NSK-birthday-attack#2]
- you need to add 
CFLAGS = -std=c++11  -c -O0 $(LIBS) 
to Makefile (both of them), since not all  compilers use by default c++11.
- What does the word seriac means?
- What is the value of the secret key s, and how you generate it?
- in line 45 and 53 of make2.cpp you wrote : 
70 if p's bits are 1024\n\
but the right one is 65 (since n=130 for p 1024 bits)
- do you use both main.cpp and main2.cpp?
- Please, add more information for the parallel version
- Is it necessary to use opensll for md5?

**Comment by vamartid** [comment]
thanks for your comment,
about the compilation error I removed the comment above the constructor of Combinations. You should not have problem now.
- **-std=c++11** done
- **seriac** changed to serial 
- **s value** Public and secret key with p (is a safe prime) are chosen so that gcd(p-1,s)==1.
I added a comment to main and to the function which set these values.
- **line 45** 70 was a mistake comment changed to 65 to all files accordingly
- **do you use both main.cpp and main2.cpp?**
main.cpp is for testing purposes and the difference is that it only runs one round of the attack.
I added that information at readme file.
- **parallel version** I added some info to the readme file, and to the func2.
- **Is it necessary to use OpenSSL for md5?**
No it is not. In this implementation we use md5-hashing so we found convenient to use OpenSSL's library for calculating it. You can always change that implementation another.
